### ISSUE TITLE
VS 2017 Community — "The extension is not installable on any currently installed products"

### ISSUE THREAD

**Issue by headjoe3** [samizzo/nshader#18]
I tried running the latest version (2.4) using the VSIX Installer, and got this error. I am using VisualStudio 2017 Community.

Install log:

3/9/2018 2:59:07 PM - Microsoft VSIX Installer
3/9/2018 2:59:07 PM - -------------------------------------------
3/9/2018 2:59:07 PM - vsixinstaller.exe version:
3/9/2018 2:59:07 PM - 15.6.152+ge95e4dd1ce
3/9/2018 2:59:07 PM - -------------------------------------------
3/9/2018 2:59:07 PM - Command line parameters:
3/9/2018 2:59:07 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\johna\Downloads\NShader.vsix
3/9/2018 2:59:07 PM - -------------------------------------------
3/9/2018 2:59:07 PM - Microsoft VSIX Installer
3/9/2018 2:59:07 PM - -------------------------------------------
3/9/2018 2:59:07 PM - Found setup instance e26cb0d0 but not in launchable state.
3/9/2018 2:59:07 PM - Initializing Install...
3/9/2018 2:59:07 PM - Extension Details...
3/9/2018 2:59:07 PM - 	Identifier         : NShader.51a01e9d-eb56-4ee2-a9fd-8212bf6bf2b1
3/9/2018 2:59:07 PM - 	Name               : NShader
3/9/2018 2:59:07 PM - 	Author             : Alexandre Mutel
3/9/2018 2:59:07 PM - 	Version            : 2.4
3/9/2018 2:59:07 PM - 	Description        : NShader is an extension to Visual Studio that provides syntax highlighting for various shader languages including HLSL - GLSL - CG
3/9/2018 2:59:07 PM - 	Locale             : en-US
3/9/2018 2:59:07 PM - 	MoreInfoURL        : https://github.com/samizzo/nshader
3/9/2018 2:59:07 PM - 	InstalledByMSI     : False
3/9/2018 2:59:07 PM - 	SupportedFrameworkVersionRange : [4.5,)
3/9/2018 2:59:07 PM - 
3/9/2018 2:59:07 PM - 	SignatureState     : Unsigned
3/9/2018 2:59:07 PM - 	Supported Products : 
3/9/2018 2:59:07 PM - 		Microsoft.VisualStudio.Pro
3/9/2018 2:59:07 PM - 			Version : [12.0,15.0]
3/9/2018 2:59:07 PM - 		Microsoft.VisualStudio.Enterprise
3/9/2018 2:59:07 PM - 			Version : [12.0,15.0]
3/9/2018 2:59:07 PM - 		Microsoft.VisualStudio.Ultimate
3/9/2018 2:59:07 PM - 			Version : [12.0,15.0]
3/9/2018 2:59:07 PM - 		Microsoft.VisualStudio.Premium
3/9/2018 2:59:07 PM - 			Version : [12.0,15.0]
3/9/2018 2:59:07 PM - 
3/9/2018 2:59:07 PM - 	References         : 
3/9/2018 2:59:07 PM - 		-------------------------------------------------------
3/9/2018 2:59:07 PM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
3/9/2018 2:59:07 PM - 		Name         : Visual Studio MPF 12.0
3/9/2018 2:59:07 PM - 		Version      : [12.0]
3/9/2018 2:59:07 PM - 		MoreInfoURL  : 
3/9/2018 2:59:07 PM - 		Nested       : No
3/9/2018 2:59:07 PM - 
3/9/2018 2:59:07 PM - 	Prerequisites      : 
3/9/2018 2:59:07 PM - 		-------------------------------------------------------
3/9/2018 2:59:07 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/9/2018 2:59:07 PM - 		Name         : Visual Studio core editor
3/9/2018 2:59:07 PM - 		Version      : [15.0.26208.0,16.0)
3/9/2018 2:59:07 PM - 
3/9/2018 2:59:07 PM - Signature Details...
3/9/2018 2:59:07 PM - 	Extension is not signed.
3/9/2018 2:59:07 PM - 
3/9/2018 2:59:07 PM - Searching for applicable products...
3/9/2018 2:59:07 PM - Found installed product - Global Location
3/9/2018 2:59:07 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by linf233** [comment]
hi
Did you solve this porblem ?
Thanks
